### ISSUE TITLE
Check marks for Stationary and AoE in Boss spell lists don't always work 

### ISSUE THREAD

**Issue by Spectre93** [j3rrr/ZeroNotes#5]
Problem: when switching to another template in the editor, the check marks in the _other_ template don't get saved (they revert to their previous state when you hit the "Update Boss Table" button.

The template that is **first there when loading** the addon **does** work, so reloading after switching templates is a temporary fix allowing you to change the marks. Only ever the first one you load into works properly and any other template doesn't retain your choices.

**Comment by j3rrr** [comment]
Most likely a problem with how WoW handles saved variables etc, but we will check if we can reproduce it. Thanks for reporting.

**Comment by j3rrr** [comment]
Fixed in latest update
